package Model;
// Generated Dec 7, 2020 8:24:16 AM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer accountId;
     private Employee employee;
     private String username;
     private String password;
     private String type;
     private String image;
     private byte[] picture;

    public Account() {
    }

	
    public Account(Employee employee, String username, String password) {
        this.employee = employee;
        this.username = username;
        this.password = password;
    }
    public Account(Employee employee, String username, String password, String type, String image, byte[] picture) {
       this.employee = employee;
       this.username = username;
       this.password = password;
       this.type = type;
       this.image = image;
       this.picture = picture;
    }
   
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }




}


