package Model;
// Generated Dec 7, 2020 8:24:16 AM by Hibernate Tools 4.3.1



/**
 * Blog generated by hbm2java
 */
public class Blog  implements java.io.Serializable {


     private Integer blogId;
     private Employee employee;
     private String blogName;
     private String blogContent;
     private byte[] image;
     private String picture;

    public Blog() {
    }

    public Blog(Employee employee, String blogName, String blogContent, byte[] image, String picture) {
       this.employee = employee;
       this.blogName = blogName;
       this.blogContent = blogContent;
       this.image = image;
       this.picture = picture;
    }
   
    public Integer getBlogId() {
        return this.blogId;
    }
    
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getBlogName() {
        return this.blogName;
    }
    
    public void setBlogName(String blogName) {
        this.blogName = blogName;
    }
    public String getBlogContent() {
        return this.blogContent;
    }
    
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }




}


