package Model;
// Generated Dec 11, 2020 10:38:08 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name="blog"
    ,catalog="dbthuongmaidientu"
)
public class Blog  implements java.io.Serializable {


     private Integer blogId;
     private String blogName;
     private String blogContent;
     private String picture;

    public Blog() {
    }

    public Blog(String blogName, String blogContent, String picture) {
       this.blogName = blogName;
       this.blogContent = blogContent;
       this.picture = picture;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BlogID", unique=true, nullable=false)
    public Integer getBlogId() {
        return this.blogId;
    }
    
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    
    @Column(name="BlogName", length=45)
    public String getBlogName() {
        return this.blogName;
    }
    
    public void setBlogName(String blogName) {
        this.blogName = blogName;
    }

    
    @Column(name="BlogContent", length=20000)
    public String getBlogContent() {
        return this.blogContent;
    }
    
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }

    
    @Column(name="Picture", length=500)
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }




}


