package Model;
// Generated Dec 7, 2020 8:24:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private String customerName;
     private String address;
     private String phone;
     private String email;
     private Integer accountId;
     private Set<Order> orders = new HashSet<Order>(0);

    public Customer() {
    }

	
    public Customer(String customerName) {
        this.customerName = customerName;
    }
    public Customer(String customerName, String address, String phone, String email, Integer accountId, Set<Order> orders) {
       this.customerName = customerName;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.accountId = accountId;
       this.orders = orders;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


