package Model;
// Generated Dec 7, 2020 8:24:16 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer employeeId;
     private String employeeName;
     private String sex;
     private String email;
     private String phone;
     private String address;
     private Integer salary;
     private Date paycheck;
     private Integer workdate;
     private Date lastAtt;
     private Set<Blog> blogs = new HashSet<Blog>(0);
     private Set<Account> accounts = new HashSet<Account>(0);

    public Employee() {
    }

	
    public Employee(String employeeName) {
        this.employeeName = employeeName;
    }
    public Employee(String employeeName, String sex, String email, String phone, String address, Integer salary, Date paycheck, Integer workdate, Date lastAtt, Set<Blog> blogs, Set<Account> accounts) {
       this.employeeName = employeeName;
       this.sex = sex;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.salary = salary;
       this.paycheck = paycheck;
       this.workdate = workdate;
       this.lastAtt = lastAtt;
       this.blogs = blogs;
       this.accounts = accounts;
    }

    public Employee(String employeeName, String sex, String email, String phone, String address, Integer salary, Date paycheck, Integer workdate, Date lastAtt) {
        this.employeeName = employeeName;
        this.sex = sex;
        this.email = email;
        this.phone = phone;
        this.address = address;
        this.salary = salary;
        this.paycheck = paycheck;
        this.workdate = workdate;
        this.lastAtt = lastAtt;
    }

    public Employee(Integer employeeId, String employeeName, String sex, String email, String phone, String address, Integer salary, Date paycheck) {
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.sex = sex;
        this.email = email;
        this.phone = phone;
        this.address = address;
        this.salary = salary;
        this.paycheck = paycheck;
    }

 
   
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getSalary() {
        return this.salary;
    }
    
    public void setSalary(Integer salary) {
        this.salary = salary;
    }
    public Date getPaycheck() {
        return this.paycheck;
    }
    
    public void setPaycheck(Date paycheck) {
        this.paycheck = paycheck;
    }
    public Integer getWorkdate() {
        return this.workdate;
    }
    
    public void setWorkdate(Integer workdate) {
        this.workdate = workdate;
    }
    public Date getLastAtt() {
        return this.lastAtt;
    }
    
    public void setLastAtt(Date lastAtt) {
        this.lastAtt = lastAtt;
    }
    public Set<Blog> getBlogs() {
        return this.blogs;
    }
    
    public void setBlogs(Set<Blog> blogs) {
        this.blogs = blogs;
    }
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


