package Model;
// Generated Dec 7, 2020 8:24:16 AM by Hibernate Tools 4.3.1



/**
 * OrderdetailId generated by hbm2java
 */
public class OrderdetailId  implements java.io.Serializable {


     private int orderId;
     private int productId;

    public OrderdetailId() {
    }

    public OrderdetailId(int orderId, int productId) {
       this.orderId = orderId;
       this.productId = productId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderdetailId) ) return false;
		 OrderdetailId castOther = ( OrderdetailId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


