package Model;
// Generated Dec 7, 2020 8:24:16 AM by Hibernate Tools 4.3.1



/**
 * Orderdetail generated by hbm2java
 */
public class Orderdetail  implements java.io.Serializable {


     private OrderdetailId id;
     private Order order;
     private Product product;
     private Integer quantityOrdered;

    public Orderdetail() {
    }

	
    public Orderdetail(OrderdetailId id, Order order, Product product) {
        this.id = id;
        this.order = order;
        this.product = product;
    }
    public Orderdetail(OrderdetailId id, Order order, Product product, Integer quantityOrdered) {
       this.id = id;
       this.order = order;
       this.product = product;
       this.quantityOrdered = quantityOrdered;
    }
   
    public OrderdetailId getId() {
        return this.id;
    }
    
    public void setId(OrderdetailId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQuantityOrdered() {
        return this.quantityOrdered;
    }
    
    public void setQuantityOrdered(Integer quantityOrdered) {
        this.quantityOrdered = quantityOrdered;
    }




}


