package Model;
// Generated Dec 7, 2020 8:24:16 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productId;
     private Category category;
     private String productName;
     private String productDescription;
     private byte[] image;
     private Float price;
     private Integer quantity;
     private String picture;
     private Set<Discount> discounts = new HashSet<Discount>(0);
     private Set<Orderdetail> orderdetails = new HashSet<Orderdetail>(0);

    public Product() {
    }

	
    public Product(String productName) {
        this.productName = productName;
    }
    public Product(Category category, String productName, String productDescription, byte[] image, Float price, Integer quantity, String picture, Set<Discount> discounts, Set<Orderdetail> orderdetails) {
       this.category = category;
       this.productName = productName;
       this.productDescription = productDescription;
       this.image = image;
       this.price = price;
       this.quantity = quantity;
       this.picture = picture;
       this.discounts = discounts;
       this.orderdetails = orderdetails;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public Set<Discount> getDiscounts() {
        return this.discounts;
    }
    
    public void setDiscounts(Set<Discount> discounts) {
        this.discounts = discounts;
    }
    public Set<Orderdetail> getOrderdetails() {
        return this.orderdetails;
    }
    
    public void setOrderdetails(Set<Orderdetail> orderdetails) {
        this.orderdetails = orderdetails;
    }




}


